language: csharp
solution: ApiHttpFormatter.sln
mono: 3.10.0

# Caching phrase.
cache:
  directories:
  - packages
  
# Installation phrase.
install:
- curl -L -o nuget.exe https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
- mono nuget.exe restore ApiHttpFormatter.sln
