language: csharp
solution: ApiHttpFormatter.sln
mono: 5.12.0

# Caching phrase.
cache:
 directories:
  - packages
  
# Install prepration phrase.
#before_install:
#- sudo apt-get install mono-complete

# Installation phrase.
install:
- curl -L -o nuget.exe https://dist.nuget.org/win-x86-commandline/v3.3.0/nuget.exe 
#https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
- mono nuget.exe restore ApiHttpFormatter.sln

script:
#- xbuild ApiHttpFormatter.sln /p:Configuration=Release /p:DeployOnBuild=true /p:PublishProfile="Folder build"
- msbuild ApiHttpFormatter.sln /p:DeployOnBuild=true /p:PublishProfile="Folder build"

before_deploy:
- cd example/back-end/ApiBackEnd/bin/Release/PublishOutput

deploy:
 provider: azure_web_apps
 skip_cleanup: true
 verbose: true
 