language: csharp
solution: ApiHttpFormatter.sln
mono: 5.4.1

# Caching phrase.
cache:
  directories:
  - packages
  
# Install prepration phrase.
#before_install:
#- sudo apt-get install mono-complete

# Installation phrase.
install:
- curl -L -o nuget.exe https://dist.nuget.org/win-x86-commandline/v3.3.0/nuget.exe 
#https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
- mono nuget.exe restore ApiHttpFormatter.sln
- xbuild /p:Configuration=Release HelloWorld.sln
