version: 1.0.{build}
image: Visual Studio 2017


build_script:
- nuget restore
- msbuild "./example/back-end/ApiBackEnd/ApiBackEnd.csproj" /p:DeployOnBuild=true /p:PublishProfile="Folder build"

artifacts:
- path: ./example/back-end/ApiBackEnd/bin/Release/PublishOutput
  name: Azure deployment
  type: WebDeployPackage
  
deploy:
- provider: WebDeploy
  server: https://apimultipartformdataservice.scm.azurewebsites.net:443/msdeploy.axd?site=ApiMultipartFormDataService
  website: ApiMultipartFormDataService
  username: $ApiMultipartFormDataService
  password:
    secure: BMVUyCtkJ9EcXWjJxv1rSkUezXyEGE098lDnGlAAcx959P8zTSfhiT9WVb0o/1EX++h7FP1ZILge3Qun4t4klw==
  artifact: Azure deployment