version: 1.0.{build}
image: Visual Studio 2017

only_commits:
 files:
  - lib/ApiMultipartFormDataFormatter/
  - example/back-end/ApiBackEnd/

environment:
  matrix:
  - projectRelativePath: '"./example/back-end/ApiBackEnd/ApiBackEnd.csproj"'
    deployOnBuild: true
    publishProfile: '"Folder build"'
  - projectRelativePath: ./lib/ApiMultipartFormDataFormatter/ApiMultiPartFormData.csproj
    deployOnBuild: false
    publishProfile: '""'
    
build_script:
- cmd: >-
    nuget restore

    msbuild %projectRelativePath% /p:DeployOnBuild=%deployOnBuild% /p:PublishProfile=%publishProfile%

artifacts:
- path: ./example/back-end/ApiBackEnd/bin/Release/PublishOutput
  name: Azure deployment
  type: WebDeployPackage
  
deploy:
- provider: WebDeploy
  server: https://apimultipartformdataservice.scm.azurewebsites.net:443/msdeploy.axd?site=ApiMultipartFormDataService
  website: ApiMultipartFormDataService
  username: $ApiMultipartFormDataService
  password:
    secure: BMVUyCtkJ9EcXWjJxv1rSkUezXyEGE098lDnGlAAcx959P8zTSfhiT9WVb0o/1EX++h7FP1ZILge3Qun4t4klw==
  artifact: Azure deployment