configuration: Release

# Before build phrase
before_build:
 - nuget restore
    
# Build phrase
build:
 publish_wap: true

before_deploy:
 - msbuild /p:DeployOnBuild=true /p:PublishProfile="Folder build" ApiHttpFormatter.sln